#!/bin/sh
#
# Configure everything for maximum power save, based on data provided by PowerTop.
#
# Wed, 19 Mar 2014 08:35:40 +0100

if [ "x$(id -u)" != "x0" ]; then
  echo "Required superuser privileges"
  exit 1
fi

echo '0'         > '/proc/sys/kernel/nmi_watchdog'
echo '1'         > '/sys/module/snd_hda_intel/parameters/power_save'
echo '1500'      > '/proc/sys/vm/dirty_writeback_centisecs'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:00.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:02.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:16.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:19.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1a.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1b.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1c.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1c.1/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1c.3/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1c.4/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1c.6/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1d.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1f.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1f.2/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:00:1f.3/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:03:00.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:0d:00.0/power/control'
echo 'auto'      > '/sys/bus/pci/devices/0000:0e:00.0/power/control'
echo 'auto'      > '/sys/bus/usb/devices/1-1.4/power/control'
echo 'auto'      > '/sys/bus/usb/devices/2-1.4/power/control'
echo 'min_power' > '/sys/class/scsi_host/host0/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host1/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host2/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host3/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host4/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host5/link_power_management_policy'
iw dev wlan0 set power_save on
ethtool -s em1 wol d
rmmod e1000e
