#!/bin/sh
#
# Gets a summary of the new MR. Designed for Freedesktop repositories.

NC='\033[0m'
BOLD='\033[1m'
BLUE='\033[0;34m'
NEW_MRS=$(git log @{1}..@{0} | grep "Part-of:" | uniq  | cut -d: -f2- | tr -d "[ <>]")

for M in $NEW_MRS ; do
  TITLE=$(curl -s $M | grep "<title>" | sed "s/<title>\(.*\) · Merge requests.*/\1/" | sed 's/\&amp;/&/g; s/\&lt;/</g; s/\&gt;/>/g; s/\&quot;/"/g; s/\&#39;/'"'"'/g')
  PRETITLE=$(echo -n $TITLE | cut -d: -f1)
  POSTTITLE=$(echo -n $TITLE | cut -d: -f2-)
  printf "$BOLD${PRETITLE+$PRETITLE:}$NC$POSTTITLE $BLUE[$M]$NC\n"
done
