#!/bin/sh
#
# Gets a summary of the new MR. Designed for Freedesktop repositories.

NC='\033[0m'
BOLD='\033[1m'

LINK_URL='\e]8;;'
LINK_TITLE='\e\\'
LINK_END='\e]8;;\e\\'

LOG_MRS=$(git log $* | grep "Part-of:" | uniq  | cut -d: -f2- | tr -d "[ <>]")

for M in $LOG_MRS ; do
  TITLE=$(curl -s $M | grep "<title>" | sed "s/<title>\(.*\) · Merge requests.*/\1/" | sed 's/\&amp;/\&/g; s/\&lt;/</g; s/\&gt;/>/g; s/\&quot;/"/g; s/\&#39;/'"'"'/g')
  POSTTITLE=$(echo -n $TITLE | cut -d: -f2-)
  PRETITLE=${TITLE%$POSTTITLE}
  printf "$LINK_URL$M$LINK_TITLE$BOLD$PRETITLE$NC$POSTTITLE$LINK_END\n"
done
