#!/bin/bash

devices=`pacmd dump | grep set-source-mute | grep input`
for dev in $devices ; do
    muted=`pacmd dump | grep "set-source-mute ${dev}" | cut -d " " -f 3`
    case ${muted} in
        "no")
            pactl set-source-mute ${dev} yes
            ;;
        "yes")
            pactl set-source-mute ${dev} no
            ;;
    esac
done

