#!/bin/bash

DEVICE=alsa_input.pci-0000_00_1b.0.analog-stereo

muted=`pacmd dump | grep "set-source-mute ${DEVICE}" | cut -d " " -f 3`
if [ ${muted} = "no" ]
then
    pactl set-source-mute ${DEVICE} yes
else
    pactl set-source-mute ${DEVICE} no
fi

